PKG_NAME=hash-sigs
PKG_URL=https://github.com/future-proof-iot/hash-sigs
PKG_VERSION=b3a9ee61f4fee062250a76fcf33144097d1db8f1
PKG_LICENSE=BSD-3-Clause

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/ -f $(CURDIR)/Makefile.hash-sigs
