PKG_NAME=hash-sigs
PKG_URL=https://github.com/cisco/hash-sigs
PKG_VERSION=7fe77790b1d16eccd70e052507b5d3f89fb0a942
PKG_LICENSE=BSD-3-Clause

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/ -f $(CURDIR)/Makefile.hash-sigs
