PKG_NAME=hash-sigs
PKG_URL=https://github.com/future-proof-iot/hash-sigs
PKG_VERSION=4ff82a8c65c0ce5e9b4a97f60828d6d4a7a4f5cd
PKG_LICENSE=BSD-3-Clause

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/ -f $(CURDIR)/Makefile.hash-sigs
