PKG_NAME=lattice-sigs
PKG_URL=https://github.com/gbanegas/dilithium_sig_clean
PKG_VERSION=9f9c35a88b78c8787e185fb96129e7b721c46767
PKG_LICENSE=BSD-3-Clause

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/ -f $(CURDIR)/Makefile.lattice-sigs
