PKG_NAME=lattice-sigs
PKG_URL=https://github.com/gbanegas/dilithium_sig_clean
PKG_VERSION=acf16f04fe35cfb82491ff3e693b7123909507ee
PKG_LICENSE=BSD-3-Clause

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/ -f $(CURDIR)/Makefile.lattice-sigs
