PKG_NAME=lattice-sigs
PKG_URL=https://github.com/gbanegas/dilithium_sig_clean
PKG_VERSION=81fd5db6848279cefc52a28504675567daa4df7f
PKG_LICENSE=BSD-3-Clause

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/ -f $(CURDIR)/Makefile.lattice-sigs
