PKG_NAME=falcon_sig
PKG_URL=https://github.com/gbanegas/falcon_sig
PKG_VERSION=d2a2fa500603178f291591ed050edc5370398f35
PKG_LICENSE=BSD-3-Clause

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/ -f $(CURDIR)/Makefile.falcon_sig
